### ISSUE TITLE
IP6 not working when IP is collection

### ISSUE THREAD

**Issue by stigzelm** [elleracompany/craft-cookie-consent#51]
So we accidentilly left on the collect IP on our site. And we noticed that when you have an IP6 you cant accept the cookie banner.

We get this error in the log:
	```
PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'ip' at row 1 in /vol/site/build.20201022-141228-43c6b1bd/vendor/yiisoft/yii2/db/Command.php:1293
Stack trace:
#0 /vol/site/build.20201022-141228-43c6b1bd/vendor/yiisoft/yii2/db/Command.php(1293): PDOStatement->execute()
#1 /vol/site/build.20201022-141228-43c6b1bd/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute('INSERT INTO `cr...')
#2 /vol/site/build.20201022-141228-43c6b1bd/vendor/yiisoft/yii2/db/Schema.php(432): yii\db\Command->execute()
#3 /vol/site/build.20201022-141228-43c6b1bd/vendor/yiisoft/yii2/db/ActiveRecord.php(600): yii\db\Schema->insert('{{%cookie_conse...', Array)
#4 /vol/site/build.20201022-141228-43c6b1bd/vendor/yiisoft/yii2/db/ActiveRecord.php(566): yii\db\ActiveRecord->insertInternal(NULL)
#5 /vol/site/build.20201022-141228-43c6b1bd/vendor/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(true, NULL)
#6 /vol/site/build.20201022-141228-43c6b1bd/vendor/elleracompany/craft-cookie-consent/src/controllers/ConsentController.php(42): yii\db\BaseActiveRecord->save()
#7 [internal function]: elleracompany\cookieconsent\controllers\ConsentController->actionUpdate()
#8 /vol/site/build.20201022-141228-43c6b1bd/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /vol/site/build.20201022-141228-43c6b1bd/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /vol/site/build.20201022-141228-43c6b1bd/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('update', Array)
#11 /vol/site/build.20201022-141228-43c6b1bd/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('update', Array)
#12 /vol/site/build.20201022-141228-43c6b1bd/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('cookie-consent/...', Array)
#13 /vol/site/build.20201022-141228-43c6b1bd/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction('cookie-consent/...', Array)
#14 /vol/site/build.20201022-141228-43c6b1bd/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#15 /vol/site/build.20201022-141228-43c6b1bd/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#16 /vol/site/build.20201022-141228-43c6b1bd/web/index.php(21): yii\base\Application->run()
#17 {main}

Next yii\db\Exception: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'ip' at row 1
The SQL being executed was: INSERT INTO `craft_cookie_consent_consent` (`site_id`, `ip`, `cookieName`, `data`, `dateCreated`, `dateUpdated`, `uid`) VALUES (1, '2001:14ba:8e5:4500:f9c3:a8eb:893b:f4f9', 'cookie-consent', '{\"global-necessary\":true,\"global-statistics\":true,\"global-marketing\":true}', '2020-10-23 13:00:33', '2020-10-23 13:00:33', '4e3dcc33-3dc7-441f-9b14-b48c7a11f236') in /vol/site/build.20201022-141228-43c6b1bd/vendor/yiisoft/yii2/db/Schema.php:674
Stack trace:
#0 /vol/site/build.20201022-141228-43c6b1bd/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `cr...')
#1 /vol/site/build.20201022-141228-43c6b1bd/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute('INSERT INTO `cr...')
#2 /vol/site/build.20201022-141228-43c6b1bd/vendor/yiisoft/yii2/db/Schema.php(432): yii\db\Command->execute()
#3 /vol/site/build.20201022-141228-43c6b1bd/vendor/yiisoft/yii2/db/ActiveRecord.php(600): yii\db\Schema->insert('{{%cookie_conse...', Array)
#4 /vol/site/build.20201022-141228-43c6b1bd/vendor/yiisoft/yii2/db/ActiveRecord.php(566): yii\db\ActiveRecord->insertInternal(NULL)
#5 /vol/site/build.20201022-141228-43c6b1bd/vendor/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(true, NULL)
#6 /vol/site/build.20201022-141228-43c6b1bd/vendor/elleracompany/craft-cookie-consent/src/controllers/ConsentController.php(42): yii\db\BaseActiveRecord->save()
#7 [internal function]: elleracompany\cookieconsent\controllers\ConsentController->actionUpdate()
#8 /vol/site/build.20201022-141228-43c6b1bd/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /vol/site/build.20201022-141228-43c6b1bd/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /vol/site/build.20201022-141228-43c6b1bd/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('update', Array)
#11 /vol/site/build.20201022-141228-43c6b1bd/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('update', Array)
#12 /vol/site/build.20201022-141228-43c6b1bd/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('cookie-consent/...', Array)
#13 /vol/site/build.20201022-141228-43c6b1bd/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction('cookie-consent/...', Array)
#14 /vol/site/build.20201022-141228-43c6b1bd/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#15 /vol/site/build.20201022-141228-43c6b1bd/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#16 /vol/site/build.20201022-141228-43c6b1bd/web/index.php(21): yii\base\Application->run()
#17 {main}
Additional Information:
Array
(
    [0] => 22001
    [1] => 1406
    [2] => Data too long for column 'ip' at row 1
)
```

**Comment by alexjcollins** [comment]
@jellingsen We're getting this issue too. Do you think you're close to being able to release the commit referenced above? Thanks!

**Comment by jellingsen** [comment]
Hi @alexjcollins ! 

Yeah, sorry. Been swamped the last few weeks. We'll get that out!

**Comment by alexjcollins** [comment]
Amazing - thanks 🙌

**Comment by jellingsen** [comment]
Released. Thank you for your patience!
